Repository JuliaMath/Combinatorics.jl, pull requests merged in 2025-05, with the labels that each got.

#146 Improve performance of `derangement`/`subfactorial` with iterative implementation
  src/factorials.jl
  test/factorials.jl
Labels: performance, bignums

#149 Improve `factorial(n, k)` performance for `BigInt`
  src/factorials.jl
  test/factorials.jl
Labels: performance, bignums

#183 ci: workaround for tagbot permissions
  .github/workflows/TagBot.yml
Labels: ci

#181 doc: add more examples and test for `partitions`
  src/numbers.jl
  src/partitions.jl
  test/partitions.jl
Labels: doc

#164 Add `multiset_permutations` method that doesn't require length
  src/permutations.jl
  test/permutations.jl
Labels: feature

#129 Bugfix: include empty combination
  src/combinations.jl
  test/combinations.jl
Labels: bug

#179 Bugfix: let `integer_partitions(0) == [Int[]]`
  src/partitions.jl
  test/partitions.jl
Labels: bug

#150 Derangements
  src/permutations.jl
  test/permutations.jl
Labels: feature
